#!/bin/bash

echo "════════════════════════════════════════════════════════════"
echo "  E-TSENA - BUILD DE L'APPLICATION"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "✅ Splash screen configuré:"
echo "   - Fond blanc (#FFFFFF)"
echo "   - Logo violet (#7C3AED)"
echo "   - Images générées dans assets/"
echo ""
echo "✅ Configuration EAS vérifiée"
echo "✅ Compte Expo: lanjaprincy"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  CHOISISSEZ LE TYPE DE BUILD"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. BUILD PREVIEW (Recommandé pour tester)"
echo "   → Crée un APK optimisé pour tests"
echo "   → Temps: ~10-15 minutes"
echo "   → Commande: eas build --profile preview --platform android"
echo ""
echo "2. BUILD DEVELOPMENT"
echo "   → Crée un APK avec outils de debug"
echo "   → Temps: ~10-15 minutes"
echo "   → Commande: eas build --profile development --platform android"
echo ""
echo "3. BUILD PRODUCTION"
echo "   → Crée un AAB pour Google Play Store"
echo "   → Temps: ~10-15 minutes"
echo "   → Commande: eas build --profile production --platform android"
echo ""
echo "════════════════════════════════════════════════════════════"
